Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: CI Pipeline for RentEase Frontend
+name: CI Pipeline for Homeyhost Frontend
 run-name: Build and Deploy RentEase Frontend by ${{ github.actor }} 🚀
 
 on:
@@ -64,7 +64,7 @@ jobs:
           password: ${{ secrets.SSH_PASSWORD }}
           script: |
             echo "Starting deployment..."
-            git config --global --add safe.directory /var/www/html/app/rentease/frontend || { echo "Failed to set safe directory"; exit 1; }
+            git config --global --add safe.directory /var/www/html/app/homyhost/frontend || { echo "Failed to set safe directory"; exit 1; }
             export NVM_DIR="$HOME/.nvm"
             [ -s "$NVM_DIR/nvm.sh" ] || curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
             source "$NVM_DIR/nvm.sh"
@@ -73,11 +73,11 @@ jobs:
             node -v
             npm -v
             git config --global credential.helper store
-            echo "https://${{ secrets.GITHUB_USERNAME }}:${{ secrets.GITHUB_PAT }}@github.com" > ~/.git-credentials
+            echo "https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PAT }}@github.com" > ~/.git-credentials
             chmod 600 ~/.git-credentials
-            cd /var/www/html/app/rentease/frontend || { echo "Failed to cd to /var/www/html/app/rentease/frontend"; exit 1; }
+            cd /var/www/html/app/homyhost/frontend || { echo "Failed to cd to /var/www/html/app/homyhost/frontend"; exit 1; }
             echo "Current directory: $(pwd)"
-            git remote set-url origin https://github.com/Techevery/RentEase_Frontend.git
+            git remote set-url origin https://github.com/Techevery/HomeHost_Frontend.git
             git fetch origin || { echo "Git fetch failed"; exit 1; }
             git checkout main || { echo "Git checkout failed"; exit 1; }
             git reset --hard origin/main || { echo "Git reset failed"; exit 1; }
